spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

#  jpa:
#    defer-datasource-initialization: true
#spring.datasource.generate-unique-name=false
#spring.datasource.name=tacocloud